### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by Vaughnsmcp** [Vaughnsmcp/PenPals#1]
Flashy go-go mission statement. "Start Here" button links to login/create account page.

**Comment by Vaughnsmcp** [comment]
create JSON file with user dummy data with five users

**Comment by Dragonbabe** [comment]
Actually it was a JavaScript file we needed not a JSON... That is my bad guys... sorry for the confusion!

**Comment by Dragonbabe** [comment]
We currently have 1 user.

**Comment by Dragonbabe** [comment]
Edgar Allen Poe

**Comment by Dragonbabe** [comment]
create space for a mission statement "why we are here " the point of our website

**Comment by Dragonbabe** [comment]
Success on all!
